#!/bin/sh

rm -rf ../ca/*  2>/dev/null || true
rm ../ca/.* 2>/dev/null || true
rm -rf ../server/*  2>/dev/null || true
rm ../server/.* 2>/dev/null || true
rm -rf ../clients/* 2>/dev/null || true
rm ../clients/.* 2>/dev/null || true

