#!/bin/sh
. ./subject

mkdir -p ../ca/
openssl genrsa -des3 -passout pass:mycapass -out ../ca/fakeCa.key 1024
openssl req -new -x509 -passin pass:mycapass -key ../ca/fakeCa.key -out ../ca/fakeCa.crt -subj "$subject" -days 36000
