#!/bin/sh
. ./subject

mkdir -p ../clients/$alias
openssl req -new -newkey rsa:1024 -passout pass:my"$alias"pass -nodes -subj "$subject" -out ../clients/$alias/$alias.csr -keyout ../clients/$alias/$alias.key
openssl x509 -req -days 36000 -passin pass:mycapass -in ../clients/$alias/$alias.csr -CA ../ca/fakeCa.crt -CAkey ../ca/fakeCa.key -CAserial ../server/$alias/$alias.srl -out ../clients/$alias/$alias.crt
cat ../clients/$alias/$alias.key ../clients/$alias/$alias.crt > ../clients/$alias/$alias.pem
openssl pkcs12 -export -in ../clients/$alias/$alias.crt -inkey ../clients/$alias/$alias.key -CAfile ../ca/fakeCa.cert -passout pass:my"$alias"pass -out ../clients/$alias/$alias.p12 -name $alias

keytool -import -noprompt -alias $alias -keystore ../server/$alias/$alias.jks -file ../clients/$alias/$alias.crt -storepass myserverpass

keytool -import -noprompt -alias ca -trustcacerts -keystore ../clients/$alias/$alias.jks -file ../ca/fakeCa.crt -storepass my"$alias"pass
keytool -import -noprompt -alias serverCert -keystore ../clients/$alias/$alias.jks -file ../clients/$alias/$alias.crt -storepass my"$alias"pass