#!/bin/sh
. ./subject

mkdir -p ../server/$alias/
openssl genrsa -passout pass:myserverpass -des3 -out ../server/$alias/$alias.key 1024
openssl req -new -passin pass:myserverpass -key ../server/$alias/$alias.key -out ../server/$alias/$alias.csr -subj "$subject"
openssl rsa -in ../server/$alias/$alias.key -passin pass:myserverpass -out ../server/$alias/$alias.key.unprotected
openssl x509 -req -passin pass:mycapass -days 36000 -in ../server/$alias/$alias.csr -CA ../ca/fakeCa.crt -CAkey ../ca/fakeCa.key -CAcreateserial -out ../server/$alias/$alias.crt
cat ../server/$alias/$alias.key ../server/$alias/$alias.crt > ../server/$alias/$alias.pem
mv ../scripts/.srl ../server/$alias/$alias.srl
openssl x509 -outform der -in ../server/$alias/$alias.pem -out ../server/$alias/$alias.der
openssl pkcs12 -export -in ../server/$alias/$alias.crt -inkey ../server/$alias/$alias.key -CAfile ../ca/fakeCa.cert -passin pass:myserverpass -passout pass:myserverpass -out ../server/$alias/$alias.p12 -name $alias
rm ../server/$alias/$alias.jks 2>/dev/null || true
keytool -import -noprompt -alias ca -trustcacerts -keystore ../server/$alias/$alias.jks -file ../ca/fakeCa.crt -storepass myserverpass
keytool -import -noprompt -alias serverCert -keystore ../server/$alias/$alias.jks -file ../server/$alias/$alias.crt -storepass myserverpass
keytool -alias $alias -destalias serverKey -importkeystore  -srcstorepass myserverpass -deststorepass myserverpass -destkeystore ../server/$alias/$alias.jks -srckeystore ../server/$alias/$alias.p12 -srcstoretype PKCS12
